version: '3'

services:

  postgres:
    image: postgres:12.4
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      default:
        aliases:
          - postgres


  backend:
    container_name: backend
    build: backend
    env_file: .env
    restart: always
    command: sh -c 'cd backend && python manage.py runserver 0.0.0.0:8000'
    volumes:
        - .:/dockyard
    environment:
      - DEV_MODE=False
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=dfgkdsfls234
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5430

    ports:
      - 8000:8000
    links:
      - postgres


